### ISSUE TITLE
Package not install in laravel version 9. show that error

### ISSUE THREAD

**Issue by Hein-Thu-Ya** [nguyendachuy/laravel-menu#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nguyendachuy/laravel-menu[2.1, ..., 2.1.1] require illuminate/support 5.* || 6.* || 7.* || 8.* -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires nguyendachuy/laravel-menu ^2.1 -> satisfiable by nguyendachuy/laravel-menu[2.1, 2.1.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require nguyendachuy/laravel-menu:*" to figure out if any version is installable, or "composer require nguyendachuy/laravel-menu:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nguyendachuy** [comment]
Hello @Hein-Thu-Ya

Sorry for the delay. I have deleted the old tags. You can now try using the 1.0 tag.

`composer require nguyendachuy/laravel-menu 1.0`

If any problem, let me know.

Thanks
