### ISSUE TITLE
Package not install in laravel version 10

### ISSUE THREAD

**Issue by abhikvnair** [nguyendachuy/laravel-menu#4]
project > composer require nguyendachuy/laravel-menu 1.0
The "1.0" constraint for "nguyendachuy/laravel-menu" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update nguyendachuy/laravel-menu
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nguyendachuy/laravel-menu 1.0 -> satisfiable by nguyendachuy/laravel-menu[1.0].
    - nguyendachuy/laravel-menu 1.0 requires illuminate/support 5.* || 6.* || 7.* || 8.* -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nguyendachuy** [comment]
Hello @abhikvnair,

I have updated it.

Thanks
